robopi:
  actuator_interface:
    loop_hz: 10 # hz
    interface_type: "velocity"
    wheels:
      - left_front_wheel_joint
      - left_back_wheel_joint
      - right_front_wheel_joint
      - right_back_wheel_joint
  gpio_wheels:
    #from gpio wiring
    left_front_wheel_joint:
      en: 21
      inF: 20
      inB: 16
    left_back_wheel_joint:
      en: 21
      inF: 20
      inB: 16
    right_front_wheel_joint:
      en: 13
      inF: 19
      inB: 26
    right_back_wheel_joint:
      en: 13
      inF: 19
      inB: 26

